name: "Setup Conan"
description: "Upgrade pip, install conan, setup remote and login to artifactory"

runs:
  using: composite
  steps:
    - name: Setup Conan
      shell: bash
      run: |
        pip install --upgrade pip
        pip install conan
        conan profile detect --force
        conan remote add edwardstock ${{ env.ARTIFACTORY_REPO_URL }}
        conan remote login -p ${{ secrets.ARTIFACTORY_API_KEY }} edwardstock ${{ secrets.ARTIFACTORY_API_USER }}
